#              ___      _   _           ___                                         Our plugins: https://alonsoaliaga.com/plugins
#             | _ ) ___| |_| |_ ___ _ _| __|__ ___ _ _  ___ _ __ _  _               Support server: https://alonsoaliaga.com/discord
#             | _ \/ -_)  _|  _/ -_) '_| _|/ _/ _ \ ' \/ _ \ '  \ || |              Youtube: https://alonsoaliaga.com/play
#             |___/\___|\__|\__\___|_| |___\__\___/_||_\___/_|_|_\_, |              Test server: plugins.alonsoaliaga.com
#                                               by AlonsoAliaga  |__/               Twitch: https://alonsoaliaga.com/twitch
#              Considering donating? https://alonsoaliaga.com/donate                Thanks for using my plugin! <3
#
# CONFIG VERSION 1.4-BETA
Messages:
  No-permission: "&cYou don't have permission to do this."
  Reloaded: "&aSome messages and options have been reloaded. Other may require a restart!"
  Invalid-player: "&cPlayer is not online!"
  Illegal-money: "&cThis money seems to be illegal. Destroy it immediately!"
  Invalid-money: "&cThis money has already expired. Contact an administrator if think this is an error!"
  Money-value: "&eThe money you have in hands worth &a${VALUE}&7 (1 item)&e."
  Money-value-more: "&eThe money you have in hands worth &a${VALUE}&e each item with a total of &a${TOTAL}&7 ({AMOUNT} items)&e."
  Help:
    Admin:
    - "&2 /bettereconomy main <player> &f- &aOpen main menu for player"
    - "&2 /bettereconomy deposit <player> &f- &aOpen deposit menu for player"
    - "&2 /bettereconomy withdraw <player> &f- &aOpen withdraw menu for player"
    - "&2 /bettereconomy reload &f- &aReload configuration (Restart recommended)"
    User:
    - "&2 /bettereconomy main &f- &aOpen main menu"
    - "&2 /bettereconomy deposit &f- &aOpen deposit menu"
    - "&2 /bettereconomy withdraw &f- &aOpen withdraw menu"
  Main:
    No-permission: "&cYou don't have permission to open main menu."
    Title: "&8Coins menu"
    Opened-target: "&6You opened main GUI for {TARGET}."
  Deposit:
    No-permission: "&cYou don't have permission to open deposit gui."
    No-permission-command: "&cYou don't have permission to open deposit gui with command."
    Title: "&8Deposit coins"
    Opened-target: "&6You opened deposit GUI for {TARGET}."
    Success: "&a${TOTAL_VALUE} added to your account."
    Error: "&cSomething went wrong, you received your items back. If problem persists, contact an administrator."
    Error-extra: "&cSomething went wrong, you received your items back but some were thrown in the floor. If problem persists, contact an administrator."
  Withdraw:
    No-permission: "&cYou don't have permission to open withdraw gui."
    No-permission-command: "&cYou don't have permission to open withdraw gui with command."
    Title: "&8Withdraw coins"
    Opened-target: "&6You opened withdraw GUI for {TARGET}."
    Not-funds: "&cNot enough funds to withdraw that amount!"
    Nothing-to-withdraw: "&cYou must select what to withdraw first!"
    Transaction-error: "&cThere was an error with transaction! If problem persists contact an administrator."
    Success: "&aYou withdrew ${AMOUNT} in money items."
    Success-extra: "&aYou withdrew ${AMOUNT} in money items. Some of them were thrown in the floor!"

Options:
  #Debug mode for certain messages. Enable only if developer asks you to do it.
  Debug-mode: false
  #To apply changes for aliases you must RESTART the server.
  #Plugman or similar plugins are NOT and will NEVER be supported.
  #Use /reload or restart your server.
  Aliases:
  - "beconomy"
  Money:
    #This is the Unique Id for ALL MONEY. If you modify this, all existing money in the server will not be
    #recognized as money after change is applied. You should change this only in 2 cases.
    #1) On setup (first time you install the plugin) to use a custom string.
    #2) If you had a serious dupe issue with the plugin OR ANY OTHER PLUGIN and you want to disable existing money.
    #You can use this tool to create a new random uuid https://alonsoaliaga.com/RandomUUID
    #WARNING! CHANGING THIS WILL MAKE ALREADY CREATED MONEY USELESS. ONLY CHANGE THIS IN EMERGENCIES.
    UUID: "e1c1a194-7e86-414f-86bb-42d82a21cfb8"
    #If enabled, plugin will prevent interaction with money items.
    #It means that if it's a usable item like eye of ender it won't be used if you right click it.
    #If item is a placeable block, players won't be able to place item on the ground.
    Prevent-interaction: true
    #This option is just to ignore uuid check in case you "have issues" with some money.
    #I highly recommend you to leave this false.
    Ignore-money-uuid: false
  Main:
    Rows: 3
    Sounds:
      Open: "CHEST_OPEN"
    Fill-empty:
      Enabled: true
      #Color for stained glass pane.
      Color: BLACK
      #Custom model data is supported for 1.14+
      #Change just in case you want to use it with a texture pack.
      Custom-model-data: 0
  Deposit:
    Sounds:
      Open: "CHEST_OPEN"
    Fill-empty:
      #Color for stained glass pane.
      Color: BLACK
      #Custom model data is supported for 1.14+
      #Change just in case you want to use it with a texture pack.
      Custom-model-data: 0
  Withdraw:
    Rows: 3
    Sounds:
      Open: "CHEST_OPEN"
      Success: "EXP_ORB"
    Fill-empty:
      Enabled: true
      #Color for stained glass pane.
      Color: BLACK
      #Custom model data is supported for 1.14+
      #Change just in case you want to use it with a texture pack.
      Custom-model-data: 0

Drops:
  Entities:
    #Enabling this will make mobs drop money items. (They MUST BE LISTED ON drops.yml)
    Enabled: true
    #If enabled. Plugin will drop the item directly on entity location.
    #If disabled (RECOMMENDED). Plugin will add the item to the items to be dropped which can be modified by other plugins.
    Drop-item: false
  WorldGuard:
    Warning:
    - "Default flag:"
    - " This is the default behavior if the flag is not specified BUT you are inside in a WorldGuard region."
    - "  true - Entities drop money items."
    - "  false - Entities don't drop money items."
    Default-flag-drop: false

Items:
  Main-gui:
    Deposit-gold:
      #Supports CUSTOM_HEAD for custom heads. Texture is required.
      Material: GOLD_BLOCK
      #Texture is required if material is CUSTOM_HEAD
      Texture: "ewogICJ0aW1lc3RhbXAiIDogMTU5NDQ0NjkyMDI5NiwKICAicHJvZmlsZUlkIiA6ICJlMWMxYTE5NDdlODY0MTRmODZiYjQyZDgyYTIxY2ZiOCIsCiAgInByb2ZpbGVOYW1lIiA6ICJBbG9uc29BbGlhZ2EiLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTY4YWE3NGNjODg1NzgwNjBkMGZlM2JkOTA4YjM0ZjY5ZjEyZTA3ZjFmODljNWRkYzE1ZTZiZjYwZjA0Y2NjNiIKICAgIH0KICB9Cn0="
      Slot: 11
      #PlaceholderAPI supported
      Displayname: "&eDeposit coins"
      #PlaceholderAPI supported
      Lore: []
    Withdraw-gold:
      #Supports CUSTOM_HEAD for custom heads. Texture is required.
      Material: CUSTOM_HEAD
      Texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmNlYjU0MDEwNGU3YmJmM2QxM2YxNTI1YWNiNzEwZTNhZDM2NWQwY2IxMjkxYWQxZjc0OGY2MDJiNzdkMyJ9fX0="
      Slot: 15
      #PlaceholderAPI supported
      Displayname: "&eWithdraw coins"
      #PlaceholderAPI supported
      Lore: []
  Withdraw-gui:
    Withdraw-gold:
      #Supports CUSTOM_HEAD for custom heads. Texture is required.
      Material: CUSTOM_HEAD
      Texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmNlYjU0MDEwNGU3YmJmM2QxM2YxNTI1YWNiNzEwZTNhZDM2NWQwY2IxMjkxYWQxZjc0OGY2MDJiNzdkMyJ9fX0="
      Slot: 22
      Enough:
        #PlaceholderAPI supported
        Displayname: "&eCoins to withdraw&7: &6${TOTAL_AMOUNT}"
        #PlaceholderAPI supported
        Lore:
        - "&eBalance&7: &a${BALANCE}"
        - "&r "
        - "&bLeft click&e to increase 1."
        - "&bRight click&e to decrease 1."
        - "&bShift-left click&e to set to 64."
        - "&bShift-right click&e to set to 0."
        - "&bMiddle click&e to set halve amount."
      Not-enough:
        #PlaceholderAPI supported
        Displayname: "&eCoins to withdraw&7: &c${TOTAL_AMOUNT}"
        #PlaceholderAPI supported
        Lore:
        - "&eBalance&7: &a${BALANCE}"
        - "&cNot enough funds!"
        - "&r "
        - "&bLeft click&e to increase 1."
        - "&bRight click&e to decrease 1."
        - "&bShift-left click&e to set to 64."
        - "&bShift-right click&e to set to 0."
        - "&bMiddle click&e to set halve amount."
    Money-item:
      #If disabled. All items will use the lore specified in their sections in money.yml under the value "Lore-withdraw".
      #If enabled. All money items in withdraw menu will have the following lore.
      Global-lore: false
      Lore:
      - "&eValue&7: &a${VALUE}"
      - "&r "
      - "&7Current amount&7: &6{AMOUNT}"
      - "&7Total value&7: &a${TOTAL_VALUE}"
  Deposit-gui:
    Deposit-gold:
      #Supports CUSTOM_HEAD for custom heads. Texture is required.
      Material: CUSTOM_HEAD
      Texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmM0ODJlM2I1YzdkNmZiNmIwMDFkZTBlM2JiZmEwOWQyODE3YTY5OGNhYTZlMzNlYjI3NmFlYTA4MTA0NDFmNiJ9fX0="
      Slot: 22
      #PlaceholderAPI supported
      Displayname: "&eConfirm deposit&7: &6${TOTAL_VALUE}"
      #PlaceholderAPI supported
      Lore: []

Permissions:
  #Permission to open main menu.
  Main-menu: "none"
  #Permission to open withdraw gui from main menu.
  Withdraw: "none"
  #Permission to open withdraw gui with the command.
  Withdraw-command: "none"
  #Permission to open deposit gui from main menu.
  Deposit: "none"
  #Permission to open deposit gui with the command.
  Deposit-command: "none"
  Admin: "bettereconomy.admin"

Updates:
  #Auto update configuration? Enabling will delete comments.
  Auto-update-configuration: true
  #Check for updates? Recommended to keep it enabled.
  Check-updates: true
  #Notify updates when player with permission joins the server?
  Notify-updates: true
  #Permission required to receive update message.
  Permission: "bettereconomy.update"
  #Message to send when update is found.
  Message: "&2[BetterEconomy] &eA new update has been found! You are using version {CURRENT}. Download version {NEW} here &c{LINK}"
